### ISSUE TITLE
Question: Billing Refund

### ISSUE THREAD

**Issue by stefanoMancon** [StephenVinouze/KinApp#7]
When the user refund the purchase 
`billingManager.restorePurchases(KinAppProductType.INAPP)
` return an empty array but if i call `billingManager.purchase(this, <your_products_id_here>, KinAppProductType.INAPP)` the response is `  KinAppPurchaseResult.ALREADY_OWNED`. How to fix it?

**Comment by Hanzala717** [comment]
> When the user refund the purchase
> `billingManager.restorePurchases(KinAppProductType.INAPP) ` return an empty array but if i call `billingManager.purchase(this, <your_products_id_here>, KinAppProductType.INAPP)` the response is ` KinAppPurchaseResult.ALREADY_OWNED`. How to fix it?

It must be fixed
